save00_path = "/home/nathan/.local/share/Steam/steamapps/compatdata/881100/pfx/drive_c/users/steamuser/AppData/LocalLow/Nolla_Games_Noita/save00/"
mods_path = "/home/nathan/.local/share/Steam/steamapps/common/Noita/mods"
workshop_path = "/home/nathan/.local/share/Steam/steamapps/workshop/content/881100"
